私信接口变更
czp-first/django-simple-notice pull request #2
Opened 2022-04-29 10:45 UTC by huashanglhc

私信接口变更

2022-04-29 11:05 UTC, rey-8lab commented on notice/forms.py
> +    title = forms.CharField(required=False, max_length=64)
title应该是必传的

2022-04-29 11:07 UTC, rey-8lab commented on notice/models.py
> +        )
这个唯一索引删掉，可能存在相同的数据

2022-04-29 11:12 UTC, rey-8lab commented on notice/views/private_notice.py
> +        data = request.POST.copy()
为什么要copy？

2022-04-29 11:14 UTC, rey-8lab commented on notice/views/private_notice.py
> +    private_notices = [PrivateNotice(**data, receiver=receiver) for receiver in receivers]
title可能要特殊处理一下，这个我再问问产品

2022-04-29 11:14 UTC, rey-8lab commented on notice/views/private_notice.py
> +    keyword = params.get('keyword')
把这个参数名换成title

2022-04-29 11:17 UTC, rey-8lab commented on notice/views/private_notice.py
> +    return change_node_status(str(request.user.pk), params)
这里写个todo吧，我好像没有想清楚，

2022-04-29 11:18 UTC, rey-8lab requested changes
整体挺好的，再修改一下。可以再严谨一些。

2022-05-05 02:19 UTC, huashanglhc commented on notice/views/private_notice.py
> +    keyword = params.get('keyword')
已修改

2022-05-05 02:19 UTC, huashanglhc commented on notice/views/private_notice.py
> +    private_notices = [PrivateNotice(**data, receiver=receiver) for receiver in receivers]
定义好之后发我一下title定义规则

2022-05-05 02:19 UTC, huashanglhc commented on notice/views/private_notice.py
> +    return change_node_status(str(request.user.pk), params)
已删除，改为todo状态

2022-05-05 03:37 UTC, rey-8lab approved these changes
ok

2022-05-05 03:37 UTC, merged